default_platform(:mac)

platform :mac do
  lane :release do
    build_mac_app(
      export_method: "developer-id",
      skip_package_pkg: true,
    )
    notarize(
      package: "MediaBar.app",
      username: ENV['APPLE_ID_EMAIL'],
      print_log: true,
    )
    sentry_upload_dsym(
      auth_token: ENV['SENTRY_AUTH_TOKEN'],
      org_slug: "mediabar",
      project_slug: "mac",
      dsym_path: './MediaBar.app.dSYM.zip',
      info_plist: './Configuration/Info.plist',
    )
  end
end
